name: frontend
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.0

dependencies:
  bloc: ^9.0.0
  dartz: ^0.10.1
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  flutter_dotenv: ^5.2.1
  get_it: ^8.0.3
  go_router: ^15.1.2
  google_sign_in: ^6.3.0
  http: ^1.4.0
  injectable: ^2.5.0
  intl: ^0.20.2
  ionicons: ^0.2.2
  sizer: ^3.0.5
  supabase_flutter: ^2.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.15
  injectable_generator: ^2.7.0
  change_app_package_name: ^1.5.0

flutter:
  uses-material-design: true
  assets:
    - .env.dev
    - .env.prod
  fonts:
    - family: Formula1Bold
      fonts:
        - asset: assets/fonts/Formula1-Bold.otf

    - family: Formula1Regular
      fonts:
        - asset: assets/fonts/Formula1-Regular.otf

    - family: Formula1Wide
      fonts:
        - asset: assets/fonts/Formula1-Wide.otf
